- name: Manage Portainer stacks
  vars:
    portainer_url: "{{ portainer_api_url | default('http://localhost:9000') }}"
  block:
    - name: Loop through defined stacks
      include_tasks: stack_single.yml
      loop: "{{ portainer_stacks }}"
      loop_control:
        loop_var: item
