# test stack creation with hashicorp http-echo service
- name: Wait for echo service
  uri:
    url: http://localhost:5678
    method: GET
    return_content: yes
  register: echo_response
  retries: 5
  delay: 2
  until: echo_response.status == 200

- name: Assert echo content
  assert:
    that:
      - "'Hello from Molecule!' in echo_response.content"
